export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";
export const SET_SELECTED_PARTNER = "SET_SELECTED_PARTNER";
export const SET_SELECTED_INVENTORY = "SET_SELECTED_INVENTORY";
export const SET_MY_ID = "SET_MY_ID";

